apiVersion: apps/v1
kind: Deployment
metadata:
  name: ttefss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ttefss
  template:
    metadata:
      labels:
        app: ttefss
    spec:
      containers:
      - image: okteto.dev/ttefss:latest
        name: ttefss
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "db55d629-d68d-4d71-9a51-dac3db806329"
        - name: Vless_Path
          value: "/vl5aa55"
        - name: Vmess_UUID
          value: "db55d629-d68d-4d71-9a51-dac3db806329"
        - name: Vmess_Path
          value: "/vm6vv66"
        - name: Share_Path
          value: "/v2link"
